# Generated by Django 5.2.12 on 2026-03-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='sku',
            field=models.CharField(blank=True, help_text='Event SKU for ticket scanning', max_length=100),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='use_stripe',
            field=models.BooleanField(default=False, help_text='Use built-in Stripe checkout for tickets'),
        ),
    ]
