# Generated by Django 5.2.12 on 2026-03-29 20:09

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_add_instagram_field'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave blank if ongoing.', null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='external_url',
            field=models.URLField(blank=True, help_text='Project website or documentation link.'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='gallery',
            field=wagtail.fields.StreamField([('image', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {'label': 'Gallery image'})}),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_type',
            field=models.CharField(blank=True, choices=[('exhibition', 'Exhibition'), ('residency', 'Residency'), ('community', 'Community'), ('digital', 'Digital'), ('research', 'Research'), ('publication', 'Publication'), ('performance', 'Performance'), ('other', 'Other')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='status',
            field=models.CharField(blank=True, choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('ongoing', 'Ongoing'), ('archived', 'Archived')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('image_caption', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'blockquote', 'code']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='collaborators',
            field=models.TextField(blank=True, help_text='Free-text list for external collaborators not in the People section.'),
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='projects.projectpage')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='people.personpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
