# Generated by Django 5.2.12 on 2026-04-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='related_posts_filter',
            field=models.CharField(blank=True, help_text="Title prefix to auto-pull related blog posts, e.g. 'COVID-19 CREATIVE OUTLET'.", max_length=200),
        ),
    ]
