# Generated by Django 5.2.12 on 2026-04-28 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_related_posts_filter'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbalImagesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('ongoing', 'Ongoing'), ('archived', 'Archived')], default='ongoing', max_length=20)),
                ('project_type', models.CharField(blank=True, choices=[('exhibition', 'Exhibition'), ('residency', 'Residency'), ('community', 'Community'), ('digital', 'Digital'), ('research', 'Research'), ('publication', 'Publication'), ('performance', 'Performance'), ('other', 'Other')], default='research', max_length=50)),
                ('intro', models.TextField(blank=True, max_length=500)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Verbal Images Database',
            },
            bases=('wagtailcore.page',),
        ),
    ]
