# Generated by Django 5.2.12 on 2026-04-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_create_verbal_images_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='show_featured_image',
            field=models.BooleanField(default=True, help_text='Show the featured image at the top of the page.'),
        ),
        migrations.AddField(
            model_name='verbalimagespage',
            name='show_featured_image',
            field=models.BooleanField(default=True, help_text='Show the featured image at the top of the page.'),
        ),
    ]
