# Generated by Django 5.2.12 on 2026-03-29 07:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_richpage'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpacePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('booking_email', models.EmailField(blank=True, max_length=254)),
                ('booking_info', wagtail.fields.RichTextField(blank=True)),
                ('floor_plan_image', models.ForeignKey(blank=True, help_text='Floor plan image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Space / Venue Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
