# Generated by Django 5.2.12 on 2026-03-29 14:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_spacepage'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Short intro sentence shown in the page header.')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 4), ('annual_report', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'blockquote', 'code']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {'label': 'Image with caption'}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'External link if document is hosted elsewhere', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('year', 5), ('title', 3), ('document', 6), ('url', 7)]], {'label': 'Annual report'})}, help_text='Main narrative body — history, mission, values, etc.')),
                ('funders', wagtail.fields.StreamField([('funder', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('logo', 1), ('url', 2), ('description', 3)]], {'label': 'Funder / partner'})}, help_text='Funders, partners, sponsors — logos and links.')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'About Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
