# Generated by Django 5.2.12 on 2026-04-17 18:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transparencypage_annualreportpage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacepage',
            name='floor_plan_extra',
            field=wagtail.fields.StreamField([('image', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {'label': 'Floor plan detail'})}, help_text='Additional floor plan / technical drawings'),
        ),
        migrations.AddField(
            model_name='spacepage',
            name='gallery',
            field=wagtail.fields.StreamField([('image', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {'label': 'Photo'})}, help_text='Additional venue photos'),
        ),
        migrations.AlterField(
            model_name='spacepage',
            name='floor_plan_image',
            field=models.ForeignKey(blank=True, help_text='Primary floor plan image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
