# Generated by Django 5.2.12 on 2026-04-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_spacepage_floor_plan_extra_spacepage_gallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transparencypage',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
