# Generated by Django 5.2.12 on 2026-04-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_transparencypage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='contact_address',
            field=models.TextField(blank=True, help_text='Physical address'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
