# Generated by Django 5.2.12 on 2026-03-29 14:29

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenCallsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Open Calls Index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OpenCallPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('deadline', models.DateField(blank=True, help_text='Application deadline. Leave blank for rolling/ongoing calls.', null=True)),
                ('call_type', models.CharField(blank=True, choices=[('residency', 'Residency'), ('exhibition', 'Exhibition Proposal'), ('commission', 'Commission'), ('research', 'Research'), ('workshop', 'Workshop Pitch'), ('other', 'Other')], default='', max_length=100)),
                ('intro', models.TextField(blank=True, max_length=500)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('eligibility', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'blockquote', 'code']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Who can apply'}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 3), ('text', 4)]], {'label': 'Eligibility block'})})),
                ('application_email', models.EmailField(blank=True, help_text='Email address for applications (used if no external form URL).', max_length=254)),
                ('application_url', models.URLField(blank=True, help_text='External application form URL (e.g. Google Form, Submittable).')),
                ('fee', models.CharField(blank=True, help_text="e.g. 'Free', '€10', 'By invitation'", max_length=100)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Open Call',
            },
            bases=('wagtailcore.page',),
        ),
    ]
