# Generated by Django 5.2.12 on 2026-03-29 04:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_items',
            field=wagtail.fields.StreamField([('featured_page', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('page_title', 0), ('description', 1), ('image', 2), ('url', 3)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(blank=True, default='See our work', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_url',
            field=models.CharField(blank=True, default='/projects/', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Cultural organisation — Vilnius'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_tagline',
            field=models.CharField(blank=True, default='Ideas Block', max_length=255),
        ),
    ]
