# Generated by Django 5.2.12 on 2026-03-29 15:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Publications Index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PublicationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('pub_type', models.CharField(blank=True, choices=[('book', 'Book'), ('catalogue', 'Exhibition catalogue'), ('zine', 'Zine / artist book'), ('journal', 'Journal / magazine'), ('report', 'Report'), ('online', 'Online publication'), ('other', 'Other')], default='', max_length=100, verbose_name='Type')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('authors', models.CharField(blank=True, help_text='Comma-separated list of authors/editors', max_length=500)),
                ('isbn', models.CharField(blank=True, max_length=50, verbose_name='ISBN')),
                ('intro', models.TextField(blank=True, max_length=500)),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'blockquote']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('price', models.CharField(blank=True, help_text="e.g. '€18', 'Free', 'Out of print'", max_length=100)),
                ('buy_url', models.URLField(blank=True, help_text='External purchase URL (e.g. bookshop, publisher)')),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Cover image')),
                ('pdf_download', models.ForeignKey(blank=True, help_text='Downloadable PDF if available openly', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'verbose_name': 'Publication',
            },
            bases=('wagtailcore.page',),
        ),
    ]
