# Generated by Django 5.2.12 on 2026-04-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='pub_type',
            field=models.CharField(blank=True, choices=[('book', 'Book'), ('catalogue', 'Exhibition catalogue'), ('zine', 'Zine / artist book'), ('journal', 'Journal / magazine'), ('report', 'Report'), ('online', 'Online publication'), ('article', 'Article'), ('album', 'Music album'), ('exhibition', 'Exhibition'), ('artwork', 'Artwork'), ('other', 'Other')], default='', max_length=100, verbose_name='Type'),
        ),
    ]
