# Generated by Django 5.2.12 on 2026-03-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='instagram',
            field=models.CharField(blank=True, help_text='Instagram handle without @, e.g. ideasblock.lt', max_length=100),
        ),
    ]
