# Generated by Django 5.2.12 on 2026-03-29 14:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('press_contact_name', models.CharField(blank=True, max_length=255)),
                ('press_contact_email', models.EmailField(blank=True, max_length=254)),
                ('press_contact_phone', models.CharField(blank=True, max_length=100)),
                ('press_kits', wagtail.fields.StreamField([('kit', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('document', 2)]], {'label': 'Press kit / document'})})),
                ('press_images', wagtail.fields.StreamField([('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('caption', 0), ('credit', 0), ('image', 1)]], {'label': 'Press image'})})),
                ('boilerplate', wagtail.fields.RichTextField(blank=True, help_text='Standard organisation description for press use (copy-pasteable).')),
                ('coverage', wagtail.fields.StreamField([('article', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.DateBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'EN', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('headline', 0), ('publication', 0), ('date', 1), ('url', 2), ('language', 3)]], {'label': 'Press article'})})),
            ],
            options={
                'verbose_name': 'Press Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
