# Generated by Django 5.2.12 on 2026-03-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('friend', 'Friend'), ('collaborator', 'Collaborator'), ('staff', 'Staff')], default='friend', help_text='Account type. Supporter/Patron status is determined by active subscription.', max_length=20),
        ),
    ]
