# Generated by Django 5.2.12 on 2026-03-29 04:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Products Index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, max_length=500)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_display', models.CharField(blank=True, help_text="e.g. '€25 / free for members'", max_length=100)),
                ('is_available', models.BooleanField(default=False, help_text='Show a purchase/registration CTA')),
                ('external_purchase_url', models.URLField(blank=True)),
                ('wp_post_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Product / Workshop',
            },
            bases=('wagtailcore.page',),
        ),
    ]
