# Generated by Django 5.2.12 on 2026-03-29 21:11

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productpage_sku_productpage_use_stripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum units/registrations. Leave blank for unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'blockquote', 'code']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {})}),
        ),
    ]
